### ISSUE TITLE
recalculating...

### ISSUE THREAD

**Issue by gknisely** [mapzen/eraser-map#364] opened 2016-02-11 02:43 UTC
Device name: Samsung Galaxy S5
Android version: 5.0
App build number: 0.4
What did you expected to happen? I tried to route to my house from work, but I needed beer first.  :smiley: 
What happened instead? App freaked when off route and I was located in a shopping area that was not mapped yet.  "Recalculating" was repeated as fast as the app could say it.  
Your origin: 319 E Fulton St, Lancaster, PA
Your destination: 413 Bunker Hill Rd, Strasburg, PA

Drove off route to: 40.03269, -76.24604

**Comment by msmollin** [comment] 2016-02-11 10:32
Duplicate of #334 - feel free to add thoughts / comments to that ticket. It is quite annoying! :)

**Closed by msmollin** 2016-02-11 10:32 UTC

**Comment by gknisely** [comment] 2016-02-11 17:51
thanks
