### ISSUE TITLE
Send raw (lat,lon) to Mapzen TbT (not nearest Search feature)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#150] opened 2015-12-01 06:04 UTC
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** I should be able to route to the place I press, not some other random kinda-but-not-nearby POI.
* **What happened instead?** When hard / long pressing around Foster Avenue in Arcata, California there aren't any nearby OSM or OpenAddresses points so instead of being able to navigate to a point along Foster Avenue, I'm taken to a  farther away cemetery that is not accessible to Foster Avenue. If I tap north of Foster Avenue a block then I get residential addresses (for that other street). For the UI, we could say "Near {Mapzen Search result}" instead of "{Mapzen Search result}".
* **Steps to reproduce:** Zoom into Arcata, California. On the north side of town near Sunset Avenue exit off US-101 is Foster Avenue. Tap west of the roundabout.
* **Attach a screenshot** See below.
* **Attach device logs** eh.

**Comment by nvkelso** [comment] 2015-12-01 06:04
https://www.openstreetmap.org/edit?#map=17/40.87979/-124.08772

**Comment by nvkelso** [comment] 2015-12-01 06:11
Greenwood Cemetery (bad):

![screenshot_2015-11-30-22-06-16](https://cloud.githubusercontent.com/assets/853051/11493600/2ad0046e-97af-11e5-8739-fa008de97678.png)

Some other cemetery (bad):

![screenshot_2015-11-30-22-07-27](https://cloud.githubusercontent.com/assets/853051/11493603/35f0232e-97af-11e5-89da-bb933d18f55a.png)


Some address on Wilson (bad):

![screenshot_2015-11-30-22-06-12](https://cloud.githubusercontent.com/assets/853051/11493598/200b24c8-97af-11e5-8fef-7ac757777a12.png)

Shay Park (okay but not great because it's kinda near that road and accessible from Foster Ave):

![screenshot_2015-11-30-22-06-29](https://cloud.githubusercontent.com/assets/853051/11493605/3cc89672-97af-11e5-8f13-81d50a40f73f.png)

**Comment by nvkelso** [comment] 2015-12-01 06:13
Another option is for Pelias to return streets and then the UI might look more like "Near {street name}", but that Pelias change seems more like a future enhancement and this bug is focused on working with what we have.

**Comment by dgearhart** [comment] 2015-12-01 13:08
+1

**Comment by ecgreb** [comment] 2015-12-01 15:54
Seems like what we need here is a threshold distance value to which we compare the result of the reverse geocode request.

```
poi = Pelias.reverse(lat, lon)

if (poi.distance < THRESHOLD) {
    route.to(poi)
} else {
    route.to(lat, lon)
}
```

I would still put this in the category of "enhancement" since the current implementation works as intended (route to the closest POI) but I agree this logic should be added prior to launch.

**Comment by mjcunningham** [comment] 2015-12-01 16:08
@ecgreb Would you imagine that being a client side thing? 

cc @riordan

**Comment by msmollin** [comment] 2015-12-01 16:08
Hmmm I think that's a good start but you probably want to make it something that isn't canonical like distance? Just thinking that distance is absolute but given the different zoom levels you might run into weirdness using absolute distance thresholds. Does that make sense?

**Comment by nvkelso** [comment] 2016-01-12 20:16
Talking with Dave on the routing team, there is an API call in Valhalla to get the nearest OSM road that we could dip into.

**Comment by riordan** [comment] 2016-01-12 20:19
There was some interest in that sort of a snap-to-road API by Zach Lieberman (School for Poetic Computation) last week.

https://twitter.com/patriciogv/status/685115020452192256

**Comment by mjcunningham** [comment] 2016-01-12 21:22
@nvkelso I'd be interested to hear more but my sense is that we should handle all the reverse logic in pelias. I feel like an additional call into valhalla could get slow.

**Comment by nvkelso** [comment] 2016-01-18 07:31
@mjcunningham Ideally Pelias would return nearest road directly (and provide back the latLng of the input, decorated if it's a "nearby" result decoration versus a 100% match result).

**Comment by nvkelso** [comment] 2016-01-18 07:56
I hit this twice again this weekend on drive and walk tests:

**1) Walking from along Valencia to Burma Love**

What I asked for:

* http://valhalla.github.io/demos/routing/#loc=17,37.767424,-122.420391&locations=[{"lat":37.75612631769532,"lng":-122.42074012756346},{"lat":37.76945108797398,"lng":-122.42217779159546}]&costing="auto"

<img width="360" alt="screen shot 2016-01-17 at 23 45 13" src="https://cloud.githubusercontent.com/assets/853051/12385786/67ae2650-bd74-11e5-85ba-bcf9cbbf8f9b.png">

What I got via Eraser Map + Pelias:

* http://valhalla.github.io/demos/routing/#loc=18,37.769341,-122.421413&locations=[{"lat":37.756075422819166,"lng":-122.42086887359618},{"lat":37.76940444274278,"lng":-122.42199540138243}]&costing="auto"

![screenshot_2016-01-16-12-19-48](https://cloud.githubusercontent.com/assets/853051/12385757/1bd7ea9a-bd74-11e5-9d9d-d55f111f04d5.png)

Burma Love has an address of `211 Valencia`, Pelias should bias the calculated (driving, bicycle, walking) access point towards Valencia! The bad access point off Clinton Park is probably arrived at from a Pelias centroid of building sent to Valhalla which snaps to nearest geometric street segment? (I had long pressed on Valencia just in front of the building for a revGeo, text search couldn't fine the restaurant.)

**2) Driving from my house to trailhead south of Pacifica**

What I asked for:

* http://valhalla.github.io/demos/routing/#loc=14,37.578392,-122.500777&locations=[{"lat":37.74452137991442,"lng":-122.42700576782227},{"lat":37.585126106780095,"lng":-122.50991821289062}]&costing="auto"

<img width="587" alt="screen shot 2016-01-17 at 23 37 27" src="https://cloud.githubusercontent.com/assets/853051/12385693/80fbcbcc-bd73-11e5-8dc3-ac6c1e7b7f8e.png">

What I got via Eraser Map + Pelias:

* http://valhalla.github.io/demos/routing/#loc=16,37.583902,-122.507869&locations=[{"lat":37.74397841428505,"lng":-122.4266195297241},{"lat":37.58475201586989,"lng":-122.5141668319702}]&costing="auto"

![screenshot_2016-01-17-10-35-58](https://cloud.githubusercontent.com/assets/853051/12385687/68073688-bd73-11e5-8bb8-830e3a3d1cf4.png)

In this last one near Pacifica, there's the **added complication** that (a) I as a customer tapped on a specific location, (b) Pelias + Eraser Map is returning another location, presumably snapped to the landuse AOI's  record, and (c) the displayed map (via vector tiles) shows an icon for the same landuse AOI that is in a different location. We should be more consistent.

**Comment by msmollin** [comment] 2016-02-07 17:49
Just wanted to +1 this. I just hit this because my house is not in OSM, so Release-0.4 snapped me to a POI that theoretically is for the entrance to my neighborhood (it's wrong, but that's another problem.)

![screenshot_20160207-115407](https://cloud.githubusercontent.com/assets/1163880/12873994/23a0b79a-cd99-11e5-80d6-27709156c9b7.png)

**Comment by zerebubuth** [comment] 2016-03-22 08:40
I also hit this while routing to a rural area. In the attached screenshot, the red ring is where I long-pressed to route to. The found location is close enough to be useful, given that I was driving from about 60 miles away. However, I think it might be confusing and frustrating for anyone who doesn't understand why they'd get the nearest geocodable POI rather than just the location they tapped.

![image](https://cloud.githubusercontent.com/assets/271360/13945970/649fa836-f009-11e5-8f49-7033f1aa607a.png)

**Comment by mjcunningham** [comment] 2016-03-22 21:35
Closing in favor of: https://github.com/mapzen/eraser-map/issues/524

**Closed by mjcunningham** 2016-03-22 21:35 UTC
Labels: launch, search
