### ISSUE TITLE
Multi Modal can get into a state where routes disappear that were originally there

### ISSUE THREAD

**Issue by msmollin** [mapzen/eraser-map#698] opened 2016-07-21 15:41 UTC
* **Device name:** 
OnePlus One
* **Android Version:** 
6.0.1
* **App build number:**
0.10.2
* **What did you expected to happen?** 
When tapping quickly between route versions (Car -> Bike -> Car -> etc.) the routes should remain accurate.
* **What happened instead?**
After enough tapping the bike route disappeared. Toggling slowly brought it back.
* **Steps to reproduce:**
Load a route that has both car and biking directions, and quickly tap between the two options.
* **Attach a screenshot**
![screenshot_20160721-113456](https://cloud.githubusercontent.com/assets/1163880/17029122/fbc96868-4f37-11e6-8d57-7249de03ec8f.png)
![screenshot_20160721-113451](https://cloud.githubusercontent.com/assets/1163880/17029132/fef6268e-4f37-11e6-8872-b2a678b34e30.png)

**Comment by sarahlensing** [comment] 2016-07-21 18:04
I've been tapping like a maniac and can't repro this. I looked at the code and can see we are "cancelling" requests each time a new route mode is clicked. @ecgreb can you see anything I'm missing in the code?

**Comment by ecgreb** [comment] 2016-07-21 18:14
I am also unable to reproduce.

We did implement pseudo-cancellation when toggling between routing modes in that if a new request is made before the original request completes then the result of the original request is ignored.

https://github.com/mapzen/eraser-map/pull/631

**Comment by msmollin** [comment] 2016-07-21 18:28
Here's me reproducing it on my Nexus 7.

https://www.youtube.com/watch?v=KaUBCI2gKyc

**Comment by ecgreb** [comment] 2016-07-25 19:42
I was just now able to reproduce. Not only route line but pins also disappeared after rapidly switching modes several times.

Possibly related to https://github.com/mapzen/eraser-map/issues/705?

![image](https://cloud.githubusercontent.com/assets/464123/17114724/287b68ea-527e-11e6-88f6-e6a9eea879d1.png)

**Comment by mjcunningham** [comment] 2016-07-26 17:47
I motion to close this in favor of https://github.com/mapzen/eraser-map/issues/705

If anyone opposes you can re-open this.

**Closed by mjcunningham** 2016-07-26 17:47 UTC
Labels: bug, ready
