### ISSUE TITLE
Stylesheet rendering differently on devices

### ISSUE THREAD

**Issue by souperneon** [mapzen/eraser-map#184] opened 2015-12-08 16:53 UTC
Manufacturer: samsung
Model: SAMSUNG-SM-G925A
Release: 5.1.1
Code name: REL
SDK: 22
Build number: master-535

Subway icons not appearing only labels are for the s6  edge. The s5 has icons appearing.

![](https://lh3.googleusercontent.com/-9OYR-1QXt_U/VmcK2wNr8FI/AAAAAAAAW7k/POIL3twe9Mw/w671-h1192-no/2015-12-08.jpg)

**Comment by souperneon** [comment] 2015-12-08 16:54
@mjcunningham can you add your device spec?

**Comment by tallytalwar** [comment] 2015-12-08 17:03
Just confirming if this is from the same zoom level?

**Comment by mjcunningham** [comment] 2015-12-08 18:37
@tallytalwar yep, we can demo IRL. On my phone i see icons and no labels and on Ekta's its labels and no icons.

**Comment by nvkelso** [comment] 2015-12-08 20:17
Probably a duplicate of: https://github.com/tangrams/eraser-map/issues/112

**Comment by blair1618** [comment] 2015-12-15 20:12
@souperneon @mjcunningham Are you able to reproduce this behavior in the current app build? Feel free to post screencaps.

**Closed** 2015-12-15 20:50 UTC
Labels: ready, rendering
