### ISSUE TITLE
Backgrounding while searching

### ISSUE THREAD

**Issue by mjcunningham** [mapzen/eraser-map#785] opened 2016-11-10 18:37 UTC
- Start typing in the search box.
- Background app.
- Relaunch
- Keyboard is up but input is not focused and you can see the map.

**Comment by sarahlensing** [comment] 2016-11-17 19:19
Unable to reproduce, closing. We can reopen a new ticket if it becomes an issue again.

**Closed by sarahlensing** 2016-11-17 19:19 UTC
Labels: bug, in progress
