### ISSUE TITLE
Labels sometimes disappear

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/eraser-map#116] opened 2015-11-09 19:11 UTC
* Device name: Samsung Galaxy Tab 4 8.0 16GB, Black
* Android version: 4.4.4
* App build number: master-442
* What did you expect to happen? Moving away from an area and then back to it shouldn't affect which labels are displayed, or shouldn't affect it very much.
* What happened instead? After zooming in and out, or panning to one side and back, such that the original tile goes offscreen or there's a zoom change, sometimes when you return there are different or fewer labels showing. When resuming (e.g: via the task switcher) sometimes no labels draw at all, until the map is moved.
* Steps to reproduce: Zoom and pan to a particular area, pan away, then pan back. Sometimes the labels will be different. Switch to another app, then back to Erasermap. Sometimes the no labels will draw.

For example (near [here](http://www.openstreetmap.org/#map=19/51.57863/-0.12430)):

![screenshot_2015-11-09-18-56-33](https://cloud.githubusercontent.com/assets/271360/11043556/3579a2bc-8715-11e5-9e3e-6250d1e60be6.png)

After panning away and back. Note that "Harris & Hoole" and "Starbucks" labels have disappeared, but the "Hornsey Town Hall" one on the right has appeared:

![screenshot_2015-11-09-18-57-06](https://cloud.githubusercontent.com/assets/271360/11043582/5755de64-8715-11e5-973d-b75aaec34463.png)

After switching to Settings and back:

![screenshot_2015-11-09-19-02-04](https://cloud.githubusercontent.com/assets/271360/11043594/634853b4-8715-11e5-9dd3-3f499b1a17d9.png)

**Comment by msmollin** [comment] 2015-11-09 19:34
My very limited knowledge of how this app is built tells me this is probably something inside of Tangram not redrawing correctly. @blair1618 might know more about it.

For what it's worth I can't reproduce this on either of my phone-sized devices (nvidia shield or OnePlus One), and my 2013 N7 is currently MIA so I can't test the experience on tablets.

**Comment by zerebubuth** [comment] 2015-11-09 19:36
No worries. I've got my tablet sitting here if there's any debugging you'd like me to do - I'm happy to load on a debug / testing version and grab some `logcat` output, if that'd help.

**Comment by blair1618** [comment] 2015-11-09 19:49
Cool, thanks for the report. This is almost certainly something to address within Tangram. Sounds like two conceptual issues:

1. Label placement is not deterministic. We understand that our implementation has no guarantees that placement will be deterministic or idempotent; it's not ideal but I think we can work with it for now.
2. Labels sometimes completely disappear. This is just your garden-variety bug :) Does this only happen when you switch applications? If so, it could be an issue with re-creating the GL context when tangram resumes. @karimnaaji might have thoughts on this.

**Comment by blair1618** [comment] 2015-11-09 20:01
Hey @zerebubuth Can you try to reproduce the label disappearance after app switching? If you get the labels to disappear completely again, move the map and see if they come back.

**Comment by karimnaaji** [comment] 2015-11-09 20:11
Yeah the labels disappearing seems to be a GL context loss related issue since I'm able to reproduce on the OS X build of Tangram after destroying the context. I'll create an issue on Tangram to follow this issue.

**Comment by zerebubuth** [comment] 2015-11-09 20:12
Okay, I'm having trouble reproducing it reliably by switching apps - it's only happened a handful of times. However, I seem to be able to reliably reproduce it by changing the orientation. For example, normal:

![screenshot_2015-11-09-20-09-34](https://cloud.githubusercontent.com/assets/271360/11045191/ea41db6c-871d-11e5-80af-3cc781208903.png)

Orient to portrait, and the labels and icons disappear:

![screenshot_2015-11-09-20-09-53](https://cloud.githubusercontent.com/assets/271360/11045204/f7ca262c-871d-11e5-91eb-b880d5af427b.png)

If I touch the map, or move it, then all the labels and icons reappear.

Unfortunately, now I seem to be stuck with a pin where I touched, and the menu bar has gone black. Probably unrelated?

![screenshot_2015-11-09-20-11-10](https://cloud.githubusercontent.com/assets/271360/11045238/24823a74-871e-11e5-9847-17219fc18c5f.png)

**Comment by blair1618** [comment] 2015-11-09 20:48
Yep, these are textbook symptoms of GL context loss. We're on it!

I would guess that the pin and the black menu bar are separate issues within the eraser-map app. 

A deeper explanation, for any interested:

OpenGL rendering requires the creation of an object called a "GL context" that represents all of the graphics-related resources that your application has access to. While a desktop computer has no trouble creating a GL context for every application that needs one, android phones (especially older ones) can sometimes run into limits with their graphics hardware. GL applications on Android are subject to having their GL context destroyed any time that the app is not currently visible, in order to free up resources for another application that needs graphics. GL context loss also happens when an application is rotated (thanks Android). Android apps using GL go to great lengths to ensure that everything can be re-initialized very quickly, and sometimes it results in quirks like this.

**Comment by msmollin** [comment] 2015-11-09 20:56
Black menu bar we've seen on other devices. Dunno if @ecgreb has had time to track it down yet.

**Comment by tallytalwar** [comment] 2015-12-01 21:34
I just did a rebuild of the last eraser-map (master) build, for it to pick latest tangram changes.

@ecgreb can you try with the last eraser-map (master-494) build if any of the context loss situations cause this issue now.

**Comment by karimnaaji** [comment] 2015-12-03 16:10
Fixed by https://github.com/tangrams/tangram-es/issues/390 once new build is pulled.

**Comment by zerebubuth** [comment] 2015-12-03 16:11
Awesome, thanks! I look forward to the next release :smile:

**Comment by tallytalwar** [comment] 2015-12-03 16:12
https://github.com/tangrams/tangram-es/pull/415 is the actual PR which fixes this :D. Will do a rebuild of master eraser-map from circle.

**Comment by ecgreb** [comment] 2015-12-03 16:19
:+1:

**Comment by zerebubuth** [comment] 2015-12-09 16:17
I just tried master-540 and it looks fixed to me.

I don't know what your issue workflow is, and whether you close issues only when they've been versioned and deployed - so feel free to dispose of this issue in whatever is the normal way for a fixed issue :smile:

**Closed** 2015-12-09 16:27 UTC
Labels: bug, launch, rendering
