### ISSUE TITLE
Old route line and new route line both display after taking a different route

### ISSUE THREAD

**Issue by rmglennon** [mapzen/eraser-map#216] opened 2015-12-21 20:25 UTC
I know there is a similar issue that was recently fixed where the new route line never displayed after rerouting, but this is slightly different because both the old and new lines display at the same time.

Manufacturer: LGE
Model: Nexus 5X
Release: 6.0.1
Code name: REL
SDK: 23
Build number: master-592

What did you expect to happen?
When I chose to go a different way, the original route line should go away and the app display a new route line after it recalculates.

What happened instead?
The existing route line still displayed on screen (the rightmost green line), along with the new route line (under the green arrow).

![image](https://cloud.githubusercontent.com/assets/4380498/11940464/b3a6d824-a7dd-11e5-83db-489c48d6e3c8.png)

Steps to reproduce:
Start a route and go a different direction than it suggests. I was navigating from Burlingame, CA to Daly City, CA and chose to take John Daly Blvd exit, instead of CA-1 and Junipero Serra Blvd.

**Comment by nvkelso** [comment] 2016-02-09 20:32
I hit this in master-865 in my drive test yesterday.

**Comment by nvkelso** [comment] 2016-02-15 22:40
Happened multiple times to me on drive tests in Phoenix using master-907. Quite confusing when the routines later meet back up!

**Comment by sarahlensing** [comment] 2016-02-22 15:38
I am unable to reproduce this. I've tried using a mock gpx file as well as walking a different route than the one given to me but haven't seen the issue.

I propose moving this to the backlog for now- we can keep an eye out for it and readdress it when its reproducable. Does that sound good to @mjcunningham @ecgreb  ?

**Comment by ecgreb** [comment] 2016-02-22 15:48
I have also been unable to repro. Agree let's back burner for now unless someone knows of a destination and gpx trace that reliably triggers?

**Comment by ecgreb** [comment] 2016-03-08 04:54
Closing since unable to replicate. When test driving we saw some scenarios similar to the screenshot above but in our case it was a single route line that wanted you to turn around and get back on the highway in the other direction since that was determined to be the shortest route. Let's reopen this if it starts popping up again and/or we can find a reproducible test case.

**Closed by ecgreb** 2016-03-08 04:54 UTC
Labels: bug, launch
